[2025-02-20T06:08:49.612+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_snowflake.load_data_to_snowflake scheduled__2025-02-19T06:08:21.996845+00:00 [queued]>
[2025-02-20T06:08:49.626+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_snowflake.load_data_to_snowflake scheduled__2025-02-19T06:08:21.996845+00:00 [queued]>
[2025-02-20T06:08:49.626+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-02-20T06:08:49.644+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_data_to_snowflake> on 2025-02-19 06:08:21.996845+00:00
[2025-02-20T06:08:49.650+0000] {standard_task_runner.py:57} INFO - Started process 12076 to run task
[2025-02-20T06:08:49.655+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_snowflake', 'load_data_to_snowflake', 'scheduled__2025-02-19T06:08:21.996845+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/api_to_snowflake.py', '--cfg-path', '/tmp/tmpbhyf87ef']
[2025-02-20T06:08:49.657+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask load_data_to_snowflake
[2025-02-20T06:08:49.721+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_snowflake.load_data_to_snowflake scheduled__2025-02-19T06:08:21.996845+00:00 [running]> on host a5ad21395fb4
[2025-02-20T06:08:49.825+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_snowflake' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T06:08:21.996845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T06:08:21.996845+00:00'
[2025-02-20T06:08:49.843+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.3, Python Version: 3.7.16, Platform: Linux-6.10.11-linuxkit-x86_64-with-debian-11.7
[2025-02-20T06:08:49.844+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-20T06:08:49.845+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2025-02-20T06:08:51.561+0000] {cursor.py:800} INFO - query: [CREATE OR HOSPITAL_MU_PUBLIC_HEALTH_MEASURES (region VARCHAR, region_code VARCHA...]
[2025-02-20T06:08:51.803+0000] {cursor.py:813} INFO - query execution done
[2025-02-20T06:08:51.812+0000] {connection.py:586} INFO - closed
[2025-02-20T06:08:52.025+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2025-02-20T06:08:52.238+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_to_snowflake.py", line 62, in load_data_to_snowflake
    cs.execute(create_table_query)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 904, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01ba8350-0000-e08b-0008-a54a0008701e: SQL compilation error:
syntax error line 1 at position 10 unexpected 'HOSPITAL_MU_PUBLIC_HEALTH_MEASURES'.
[2025-02-20T06:08:52.259+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_snowflake, task_id=load_data_to_snowflake, execution_date=20250219T060821, start_date=20250220T060849, end_date=20250220T060852
[2025-02-20T06:08:52.324+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task load_data_to_snowflake (001003 (42000): 01ba8350-0000-e08b-0008-a54a0008701e: SQL compilation error:
syntax error line 1 at position 10 unexpected 'HOSPITAL_MU_PUBLIC_HEALTH_MEASURES'.; 12076)
[2025-02-20T06:08:52.379+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-20T06:08:52.409+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
